### ISSUE TITLE
Discussion: what to return when reading cfg file

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#111]
If we read a `.CFG` file using `MAGICCInput`, what should we return? Simply the namelist in metadata and the `.df` attribute being `None`?

Whatever we decide, I'll implement as part of #108

**Comment by rgieseke** [comment]
It's not an MAGICC input technically, it's a config file in Namelist format right?

**Comment by znicholls** [comment]
> It's not an MAGICC input technically, it's a config file in Namelist format right?

Yep. I guess it depends how you think about these things. My actual plan was to eventually rename `MAGICCInput` to `MAGICCData` and then just set it up so it can read everything (input files, namelist configs, output files).

**Comment by rgieseke** [comment]
So, after discussing with @znicholls: CFG should throw an error with MAGICCInput, maybe MAGICCConfig or something,  returning a Namelist

**Comment by znicholls** [comment]
closed by #108
