### ISSUE TITLE
Docs to track

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#117]
Which docs should we track in the repo?

**Comment by rgieseke** [comment]
Can you elaborate?

**Comment by znicholls** [comment]
there's like a zillion things in the `docs` and `docsrc` folders, do we want them all in the repo?

**Comment by rgieseke** [comment]
`docsrc`:

api.md     pymagicc.api.md     pymagicc.input.md
index.md@  pymagicc.config.md  pymagicc.md

The md files are auto-generated so one could argue they don't need to exist in the repo ... Not sure if they help with debugging output problems. 
+1 for one for removing and ignoring them

**Comment by znicholls** [comment]
ok can you add whatever we should ignore/remove in #118, I still don't really understand what we should/shouldn't keep

**Comment by rgieseke** [comment]
`docs`:

this should contain everything that is needed to display the site, both for being served via GitHub pages and locally for people who cloned the repo.

If anything is not used or needed it can go.

**Comment by rgieseke** [comment]
Will do!

**Comment by znicholls** [comment]
yep closed by #118
