### ISSUE TITLE
Improve missing MAGICC7 message in tests

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#124]
With MAGICC7 being skipped if not available in the tests, i'm trying to find a more descriptive error message than:

>SKIP [5] /Users/robert/Work/pymagicc/tests/test_api.py:27: MAGICC 7 is not available

It would be run if an environment variable pointing to it were set, right?

**Comment by znicholls** [comment]
I believe so. That was going to be part of #126 so happy to assign to me?

**Comment by rgieseke** [comment]
Not sure how this is related to #126 -- i was thinking of saying something like

"No MAGICC7 binary set. See ..." - we should maybe put this somewhere in the docs.

**Comment by znicholls** [comment]
> Not sure how this is related to #126

As part of that process, I'm going to have to test whether my written SCEN7 files run with MAGICC7. Hence I"ll need to get these messages set up better and sort out the MAGICC7 API (including the docs).
