### ISSUE TITLE
Simplify Doc building

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#129]
Maybe we should have a commit-hook to re-build the docs?

Should we have the master branch reflect the latest released version? What's available at https://openclimatedata.github.io/pymagicc/ is what is on Master but isn't what people pip installed.
We could consider having a dev branch. 

Or, probably a good solution too, have building the docs a part of "publish-on-pypi" packaging ...

Locally, one can always build the docs if needed.

I'd be in favor of the "on-update" i think.
Thoughts @znicholls

**Comment by znicholls** [comment]
I quite like the idea of having a `dev` branch. That way what people see when they land on `master` is what they get from `pypi` and what they get if they use the latest release and it's clear just how far things are behind (although this isn't what pandas does so might fail that test of yours...)

Then I'd just have building the docs be part of publish-on-pypi, as you say  can always build locally for dev purposes.

**Comment by rgieseke** [comment]
I like the idea of a `dev` branch too, but I think rapid Pymagicc development won't continue forever, i expect it to stop as MAGICC7 stabilises ... Having a `dev` branch would likely complicate things for the occasional contributor so I'd think we should stick with `master` and have frequent releases (as we currently do) ...

**Comment by rgieseke** [comment]
I'll look into displaying the version number in the API docs, this should be useful ...

**Comment by rgieseke** [comment]
Closing, done in #130
