### ISSUE TITLE
Improve documentation for constants or dictionaries

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#134]
With Pydocmd it doesn't seem to be easy to document constants or dictionaries with docstrings (it seems to be possible with Sphinx or using module docstrings).

One option could be to document them in separate pages in the docs, which could also provide more context.

Example: https://github.com/openclimatedata/pymagicc/commit/0d0938555d9d752a8cbe970c4ba56b2f18de9f69#diff-2d17278517c38d63c1d4109dc026d689R19

**Comment by znicholls** [comment]
Looking at pint's docs, there are some super nice features (e.g. being able to look at different versions of docs, documenting constants) of sphinx. Given the expertise we have in @lewisjared and @swillner could it be worth moving to sphinx docs?

**Comment by rgieseke** [comment]
Yes! @swillner did some great work on OpenSCM and Pyhector and it would be beneficial to only have *one* setup to understand ...

**Comment by rgieseke** [comment]
work has started in "sphinx-docs" branch

- [ ] make sphinx make sub-task of main Makefile

**Comment by swillner** [comment]
Numpy style and Sphinx setup is done now...

**Comment by rgieseke** [comment]
woot woot!

**Comment by rgieseke** [comment]
I think this can be closed (#141)
