### ISSUE TITLE
Review notebook testing

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#137]
Currently notebook testing is spread out in too many folders and the checking of outputs and filtering with `nbval` is fiddly.

Maybe it's enough to use `nbconvert` or `papermill` for testing that no unexpected exceptions occur.

**Comment by rgieseke** [comment]
https://github.com/openclimatedata/pymagicc/blob/master/notebooks/tests_sanitize.cfg

https://github.com/openclimatedata/pymagicc/blob/master/scripts/test_notebooks.sh

Should probably both go into `tests`.

**Comment by rgieseke** [comment]
"lax" testing might be good enough.

> There is also an option --nbval-lax, which collects notebooks and runs them, failing if there is an error. This mode does not check the output of cells unless they are marked with a special #NBVAL_CHECK_OUTPUT comment.

```
$ py.test --nbval-lax my_notebook.ipynb
```

https://nbval.readthedocs.io/en/latest/

**Comment by znicholls** [comment]
> "lax" testing might be good enough

I'm on the fence about this one. We're going to look pretty stupid if our notebooks don't do what we say they should...

**Comment by znicholls** [comment]
if it were easy to automate it's a handy extra check but also happy to enforce that all stuff should be properly tested...

**Comment by znicholls** [comment]
discussing with @rgieseke: what we have now makes sure that our notebooks will work with binder and our regular expressions in `notebooks/test_sanitize.cfg` are maintainable. If things become too complex in future we will reconsider, closing for now.
