### ISSUE TITLE
Move to one backend, not two

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#161]
This will be major breaking change of v2.0.0, makes our lives simpler re maintenance and more consistent for users (also us).

**Comment by rgieseke** [comment]
You mean scenario DataFrame structure, or something else?

**Comment by znicholls** [comment]
I mean e.g. we get rid of `pymagicc.read_scen_file` and only offer reading via `pymagicc.io` (but will do the same for `pymagicc.run` and `pymagicc.api`)

**Comment by znicholls** [comment]
Fiddling around now, there's an extra reason to do this. The type of file you write depends on which MAGICC version you're using. More specifically, a `HIST_EMIS` file has a namelist which includes the flags `THISFILE_DATAROWS` and `THISFILE_REGIONMODE` when it's being used with MAGICC7 but does not include them when being used with MAGICC6. I feel more and more like we should split MAGICC6 and MAGICC7 capabilities more somehow. Maybe MAGICCData should only be accessible via a MAGICC instance so it's always clear what kind of MAGICC you want to write files for?
