### ISSUE TITLE
Usage of `set_emission_scenario_setup`

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#179]
Does the config_dict have to be coupled to this?
Can it be empty? @znicholls

```python
def set_emission_scenario_setup(self, scenario, config_dict):
        """Set the emissions flags correctly.

        Parameters
        ----------
        scenario : :obj:`pymagicc.io.MAGICCData`
            Scenario to run.

        config_dict : dict
            Dictionary with current input configurations which is to be validated and
            updated where necessary.

        Returns
        -------
        dict
            Updated configuration
        """
```

**Comment by znicholls** [comment]
> Does the config_dict have to be coupled to this?

Yes, you need to make sure you're using the Pymagicc scenario and not whatever someone left there previously. If you want to use a scenario which is already written to file, put `scenario=None` in your `run` call and `file_emisscen="SCENNAME.SCEN"` in your input parameters or change line 190-191 of `pymagicc/core.py` from 

```python
if scenario is not None:
    kwargs = self.set_emission_scenario_setup(scenario, kwargs)
```

to something like

```python
if scenario is str:
    kwargs["file_emisscen"] = scenario
elif scenario is not None:
    kwargs = self.set_emission_scenario_setup(scenario, kwargs)
```

**Comment by znicholls** [comment]
@rgieseke can we close this?

**Comment by rgieseke** [comment]
Probably as i don't understand the problem anymore ... we can re-open later if necessary.
