### ISSUE TITLE
MAGICC7 compatibility

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#20]
General question, @lewisjared @znicholls -- might be helpful for decisions on how to make design decisions.

Do we need to maintain MAGICC6 compatibility once MAGICC7 is publicly available?

Will there be a need to run both from one installation? Do you need this to run regressions tests/comparisons for MAGICC7?

One could always install version 1.x and run MAGICC6, might mean separate Virtualenvs if you actually do need both but I'd think that would be fairly rare.

**Comment by znicholls** [comment]
Great question, backwards compatibility is not something we've done well with MAGICC before I don't think. Maintaining it will require some head scratching but it might be worth it.

I guess ultimately it depends how much you want to be able to compare the two versions and how easily. Given MAGICC6 was so heavily used in AR5 I doubt people will lose interest in it anytime soon. I would obviously enjoy the ability to compare them easily (i.e. without switching environments) but I don't think this is compulsory. I also think if we don't maintain MAGICC6 compatibility then we may lose the ability to run it which could be annoying in some cases.

Thoughts @lewisjared @rgieseke ?

**Comment by lewisjared** [comment]
My view is that they are sufficiently close that the benefits of being able
to run both models using the same codebase is greater than the cost of the
added complexity. Especially if we can hide that complexity from the high
level functions.

**Comment by znicholls** [comment]
I'd agree with that

**Comment by znicholls** [comment]
Obviously it's your project robert so I'm happy to follow your lead and
don't want to tread on toes

**Comment by rgieseke** [comment]
> Obviously it's your project robert so I'm happy to follow your lead and
don't want to tread on toes

No, it's for everyone who wants use it (and everyone is free to fork and modify) -- I just try to keep maintainable what I'm currently maintaining :-)

It seems clear that we all want and could make use of having both MAGICC6 and MAGICC7 included!

**Comment by znicholls** [comment]
Ok great let's go for it then

**Comment by znicholls** [comment]
@rgieseke can we close this? Or not until we are shipping with a MAGICC7 executable?

**Comment by rgieseke** [comment]
I think we're sufficiently discussed and now have MAGICC7 compatibility in ...
