### ISSUE TITLE
Windows packaging

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#221]
**Describe the bug**

Installing from master is not possible on windows as the required `.json` and `.DAT` files are not being bundled.

**Failing Test**

Please put the code (ideally in the form of a unit
test) which fails below

```
pip install git+https://github.com/opensclimatedata/pymagicc.git@master
```

```
import pymagicc
```

Import error here

**Expected behavior**

We should be able to import pymagicc.

**Screenshots**

**System (please complete the following information):**

 - OS: Windows
 - Python and Pymagicc version [e.g. Python 3.5]

**Additional context**

Part of a solution could also be lazy loading these files so they're not loaded on import, speeding everything up.

**Comment by lewisjared** [comment]
Lucky me

**Comment by znicholls** [comment]
part of this solution could also be setting up nightly pip install tests on travis (which can now run on windows, osx and linux and I am happy to have a look at or maybe @rgieseke is keen)

**Comment by rgieseke** [comment]
Not sure i follow - daily (or weekly) pip install tests on Travis could help with being aware of changing/breaking dependencies (like Pandas changing something). 
You mean we include testing a PyPI install (from GitHub) as part of the normal test suite somehow (or in Travis) on every push to master?

**Comment by znicholls** [comment]
>  daily (or weekly) pip install tests on Travis could help with being aware of changing/breaking dependencies (like Pandas changing something).

Yes. Probably weekly pip install tests (from both PyPI and the master branch) on Travis would be good. 

> You mean we include testing a PyPI install (from GitHub) as part of the normal test suite somehow (or in Travis) on every push to master?

No not this one (it's possible but not what I meant).

**Comment by lewisjared** [comment]
#222 Fixes the issue with packaging under windows, but doesn't add any extra testing steps

**Comment by znicholls** [comment]
> but doesn't add any extra testing steps

Ok, an easy solution for that isn't clear to me anyway so let's leave it
