### ISSUE TITLE
Run with `out_forcing=1`

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#230]
**Describe the bug**

As it stands, if I run with `out_forcing=True`, the run fails. 

**Failing Test**

```python
with MAGICC6() as magicc:
    magicc.run(out_forcing=1)
```

**Expected behavior**

The run should happen and I should get back an `MAGICCData` object with all the forcing timeseries. 

**Screenshots**

**System (please complete the following information):**

 - OS: Linux
 - Python and Pymagicc version: Python 3.7, pymagicc 2.0.0-alpha.1+142.g2a2d1a5.dirty

**Additional context**

I think reading in the sub-annual volcanic forcing data is causing the issue here.

**Comment by znicholls** [comment]
@lewisjared any chance you can have a look at this?

**Comment by lewisjared** [comment]
Is a valid option upsampling monthly mean values to annual means? or just ignoring it unless it is explicitly loaded...

**Comment by znicholls** [comment]
> Is a valid option upsampling monthly mean values to annual means? or just ignoring it unless it is explicitly loaded...

Both valid. At the moment I think I'd prefer to just throw a `NotImplementedError` if people try and load `DAT_VOLCANIC_RF.OUT` which tells them it can't be read and that they should read `DAT_VOLCANIC_ANNUAL_RF.OUT` instead if they want an indication of what volcanic RF is doing.
