### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#24]
@rgieseke @lewisjared 

How would you feel about starting to refactor the tests to make them scale slightly more easily? In my [MATLAB code to write files for CMIP6 stuff](https://gitlab.com/znicholls/object_oriented_simcap/project_members) I ended up having something like:

```
tests
|--- writer_tests
|--- reader_tests
|--- plotter_tests
etc.
```

I felt this made it much easier to keep track of what was going on rather than just having one big `test_everything` file.

**Comment by rgieseke** [comment]
Sure! Go for it, the more tests the better :-)
I think with the module structure Pytest should pick them up the same as now.

**Comment by znicholls** [comment]
Ok perfect, please forgive some of my schoolboy errors in the repository linked above. Still learning

**Comment by rgieseke** [comment]
No worries, all this Matlab is foreign to me anyway ;-)

**Comment by lewisjared** [comment]
@rgieseke I feel the same about Matlab.. 

My personal preference, to throw another one into the hat, is to have a tests folder which looks like:
```
tests
|--- pymagicc
     |--- test_compat.py
     |--- test_run.py
|--- integration
```
Where the tests in pymagicc follow the structure of the packages and modules within pymagicc. This makes it easier to find the tests associated with particular parts of the package.

**Comment by znicholls** [comment]
That way also works.

To make sure I understand correctly, `tests/pymagicc` then  contains our
unit tests whilst `tests/integration`contains our API tests (effectively)?

**Comment by lewisjared** [comment]
Correct. It allows for more than one package being in the root directory

**Comment by znicholls** [comment]
wicked

**Comment by znicholls** [comment]
@rgieseke can we close this?

**Comment by rgieseke** [comment]
I guess ...
