### ISSUE TITLE
All the objects are imported as dicts.

### ISSUE THREAD

**Issue by Shivamshaiv** [openclimatedata/pymagicc#255]
No code in the documentation works for me. I am running Pymagicc 1.3.2 on Google Collab with Wine properly installed.
The problem seems to be, that all the default objects in Pymagicc seem to be imported as dictionaries.

`import pymagicc`
`print(pymagicc.__version__)`
`from pymagicc import rcp26`
`type(rcp26)`

The output is

> 1.3.2
dict

**Comment by rgieseke** [comment]
I think pre-2.0 development there were no docs on Readthedocs, thus the examples on Readthedocs will only work with the 2.0 pre-release version.

You can install them with pip with the `--pre` option.

**Comment by znicholls** [comment]
@Shivamshaiv I'm closing this for now (and assuming @rgieseke's answer worked). Please open if issues are ongoing.
