### ISSUE TITLE
Dealing with two versions of MAGICC

### ISSUE THREAD

**Issue by lewisjared** [openclimatedata/pymagicc#26]
As a user of pymagicc I would like to be able to run both MAGICC6 and MAGICC7 scenarios in the same interpreter
As a magicc developer I want to be able to dynamically specify a local version of MAGICC which is used with pymagicc

This would currently be possible using our MAGICC_EXECUTABLE environment variable, but it isn't a nice API. You would have to update `os.environ` between simulations. 

Perhaps we actually need two configuration parameters `MAGICC6_EXECUTABLE` and `MAGICC7_EXECUTABLE`. The low level API then chooses the appropriate executable and as a byproduct already knows which version of MAGICC it is using! This suggests that we might need a more complex `config` handling methods sooner than I anticipated

**Comment by rgieseke** [comment]
Two ideas/questions:

Couldn't `MAGICC.__init__()` detect the version? If `root_dir` is not None it will try to detect the version?

Could we get the MAGICC core devs agree to a convention to call MAGICC7 binaries `magicc7.exe` or `magicc7`?

**Comment by lewisjared** [comment]
It can be even simpler if we don't have to detect the version, but rather explicitly define it. I like the idea of being able to do the following:
```
from pymagicc import MAGICC6, MAGICC7
with MAGICC6() as p:
    p.run()

with MAGICC7 as p:
    p.run()
```
For that to work we have to track two separate MAGICC installations and pass either a version or path to `MAGICC.__init__()`. The default settings will work for 9/10 users

The code could look something like:
```
class MAGICC7(MAGICC):
    version = 7
    executable = config['MAGICC7_EXECUTABLE']

class MAGICC6(MAGICC):
    version = 6
    executable = config['MAGICC6_EXECUTABLE']
``

**Comment by lewisjared** [comment]
The executable naming is a @znicholls question

**Comment by znicholls** [comment]
I really like the idea of 'with class as x' statements.

We can call magicc executable whatever you want. Just let me know and I'll recompile. Malte won't care either, he either seperately compile or change the one line he needs to in his wrappers

**Comment by lewisjared** [comment]
I have added the MAGICC6 and MAGICC7 classes in #32. Some feedback would be great!
