### ISSUE TITLE
Pinned Pandas

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#260]
Pandas is now pinned to a specific version.

https://github.com/openclimatedata/pymagicc/pull/259/commits/5c804468b415de236964641bf9b2c41d1a3e571c

Pyam itself is requiring Pandas>0.24 so maybe that's enough @znicholls @lewisjared ?

https://github.com/IAMconsortium/pyam/commit/3a83f912ff2b5e59b6a39eddefdbb7b2fb42a86e

**Comment by znicholls** [comment]
In my experience it has to be 0.24.2 (and the pyam constraint is wrong), if
others work we can relax it though
