### ISSUE TITLE
Config Module

### ISSUE THREAD

**Issue by lewisjared** [openclimatedata/pymagicc#27]
We need a way of accessing configuration from anywhere within `pymagicc` in a consistent manner. This state should not be stored in the root `__init__.py` as that would cause lots of circular dependencies (Module A imports Module B which imports Module A). There is a need to define default config, long-lived somewhat static config and to be able to override these values dynamically. Having a separate module with a simple interface will hide the complexity of this.

Here is how I propose that we lookup configuration variables in other parts of the library. The config object looks like a `dict`, but it knows how to find the appropriate parameter value.
```
from  pymagicc.config import config
executable = config['MAGICC6_EXECUTABLE']

```

Any feedback on the API?

**Comment by lewisjared** [comment]
That is what I meant!. Edited

**Comment by rgieseke** [comment]
Done in #32
