### ISSUE TITLE
Automatic linting

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#30]
- automatic linting (PEP8 and docstyle) would be useful
- either automatic on PRs or at least documented and callable from the `Makefile`

**Comment by znicholls** [comment]
Callable from the `Makefile` is done thanks to you, do you want to add it on PRs or shall we close?

**Comment by rgieseke** [comment]
Flake8 needs to be configured to respect `black` defaults

**Comment by rgieseke** [comment]
Maybe like this: https://github.com/ambv/black/blob/master/.flake8

**Comment by znicholls** [comment]
> Flake8 needs to be configured to respect black defaults

I don't understand, where does Flake8 come into it?

**Comment by rgieseke** [comment]
Yes, automatic might be an option but i think it shouldn't block merging

**Comment by znicholls** [comment]
> Yes, automatic might be an option but i think it shouldn't block merging

so what do we do with this issue then?

**Comment by znicholls** [comment]
Given we now have black and flake8 linting, do we close this or block merges that fail? I think we should chose one or the other.

**Comment by rgieseke** [comment]
Let's close this!
