### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#36]
A general question, with Numpy dropping Python 2 support in 2019 (https://docs.scipy.org/doc/numpy/neps/dropping-python2.7-proposal.html) and Pandas (https://pandas.pydata.org/pandas-docs/stable/install.html)

> The final release before December 31, 2018 will be the last release to support Python 2. The released package will continue to be available on PyPI and through conda.
>
>Starting January 1, 2019, all releases will be Python 3 only.

Since there are very few users of Pymagicc right now I propose we drop Python 2 support now.
Any project starting now will likely be in Python3. People who *need* Python2 for some reason can still install an old Pymagicc version.

This would allow us to use e.g. (the very nice) `pathlib` or `unittest.mock` without having to import/install compatibility backports.

Thoughts, @lewisjared @znicholls @matthiasmengel?

**Comment by rgieseke** [comment]
Pinging @anauels -- Do you use Pymagicc and/or would need Python 2 be supported?

**Comment by lewisjared** [comment]
I'm happy to drop py2, but my only criticism is that there is such a low overhead from the compatibility it doesn't really limit what can be done. Especially since travis checks py2.7 compatibility.

**Comment by hugovk** [comment]
Here's the pip installs for pymagicc from PyPI for June 2017 - May 2018:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |  33.87% |             21 |
| 2.7            |  30.65% |             19 |
| 3.5            |  19.35% |             12 |
| 3.4            |  16.13% |             10 |
| Total          |         |             62 |

Source: `pypinfo --start-date 2017-06-01 --end-date 2018-05-31 --percent --markdown pymagicc pyversion`

**Comment by rgieseke** [comment]
Thanks for sharing @hugovk but I'm not sure how useful this is for such a decision, see also: https://github.com/openclimatedata/pymagicc/issues/36#issuecomment-399875263

Do you still use the Python 2 version?

**Comment by hugovk** [comment]
Hi, it shows that a good majority (~70%) are for Python 3, supporting dropping Python 2.

See also http://python3statement.org (and https://pythonclock.org :)

---

Some good points, although that SO answer is a bit old (June 2016, quoting a May 2013 message):

> There are numerous reasons for their removal/deprecation some of which
> are:
>
>* Technically hard to make work with the new CDN
>   - The CDN is being donated to the PSF, and the donated tier does not offer any form of log access
>   - The work around for not having log access would greatly reduce the utility of the CDN

No longer applies: the new statistics are from a [BigQuery database, capacity donated to the PSF by Google](https://mail.python.org/pipermail/distutils-sig/2016-May/028986.html) (May 2016).

>* Highly inaccurate
>   - A number of things prevent the download counts from being inaccurate, some of which include:
>      - pip download cache
>      - Internal or unofficial mirrors
>      - Packages not hosted on PyPI (for comparisons sake)
>      - Mirrors or unofficial grab scripts causing inflated counts (Last I looked 25% of the downloads were from a known mirroring
> script).

At least downloads from mirrors are excluded from these figures. Only downloads via pip are included.

>* Not particularly useful
>   - Just because a project has been downloaded a lot doesn't mean it's good
>   - Similarly just because a project hasn't been downloaded a lot doesn't mean it's bad

These numbers aren't being used to claim one project is better than another, rather to get a general idea of what Python versions are being used by installers.


---

No, I'm not using Python 2 any more, only Python 3.

**Comment by rgieseke** [comment]
Alright, let's do this ... continuing in #51 !
