### ISSUE TITLE
Expose more MAGICC input files

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#37]
**Is your feature request related to a problem? Please describe.**

I'd like to read and probably change (e.g. for sensitivity analyis) more of the input files that ship with MAGICC. Currently only parameters and scenarios are exposed.

**Describe the solution you'd like**

Not sure about nicest API yet.

**Describe alternatives you've considered**

It's possible to read the files manually.

**Comment by lewisjared** [comment]
Currently in `run` a scenario file is read and then written as `SCENARIO.SCEN`. As a start we can skip that step and just point to the correct file using the magicc configuration. It would be nice to offload as much as possible to the magicc configuration through #39.

Perhaps the easiest way to start is directly writing MAGCFG_USER.CFG instead of MAGTUNE_SIMPLE.CFG. The default USER config that is shipped with magicc is not compatible with pymagicc so this would save an additional install step. It would also make the runs completely reproducible as there aren't any hidden user specific things in USER which make it through to the final configuration. @znicholls It would be great to try and simplify the default USER.CFG that is shipped as much as possible before releasing MAGICC7 as it all seems to be defaults rather than actual user configuration. It adds another level of redirection which is hard to reason about.

**Comment by rgieseke** [comment]
Simplifying the MAGCFG config is definitely a worthy goal :-)

I'm not sure I understand the `SCENARIO.SCEN` workflow, originally my idea was to create a copy of a MAGICC package which would still be self contained, i.e. going to the directory and running `magicc.exe` would produce the same output as when run from Pymagicc.

**Comment by znicholls** [comment]
As far as I understand, once you have a compiled binary, we could strip
things back to the point where all the package writes everything. I'm not
sure if that's a good idea but it's possible.

So given we can do whatever we want, the question is what should we do. I
quite like the idea of shipping with a single set of defaults ie one
default years name list, one default config and one default set of input
emissions. I would probably also include all of the rcps and all of the
ssps and that would probably cover it for me.

If we don't ship anything else, it will be much more obvious what is going
on. As Robert says, that can only be good.

**Comment by lewisjared** [comment]
I  think the `SCENARIO.SCEN` workflow can be removed and replaced with directly referencing the appropriate SCEN/SCEN7 file. That way the ability to read/write SCEN/SCEN7 is an optional extra and not needed in the day to day operation of pymagicc

So do you foresee a "custom" magicc7 distribution to be bundled in pymagicc as well? Custom in the sense that the bundled config/tunings are stripped down to the essentials and made to work out of the box with pymagicc. MAGICC7 install externally to pymagicc would still require manual setup as the USER namelist doesn't integrate with pymagicc.

It would be great if the core configuration (years and user namelists) were explicitly created in the copied run directories. This would ensure that pymagicc could use any magicc distribution. I see the MAGICC executable and tuning files (IN, SCEN, SCEN7) as being seen as immutable and released together. The USER config is just to connect the dots and change parameters so should be as simple as possible (in my opinion).

**Comment by rgieseke** [comment]
To me the DataFrame based scenario workflow is pretty crucial to what Pymagicc brings to the table, but I think being able to address SCEN files directly can coexist with DataFrames as discussed in https://github.com/openclimatedata/pymagicc/issues/21

**Comment by znicholls** [comment]
Coming back to the issue description (briefly before i veer off again), I think we need to define which inputs we want to expose. 'More' is too vague and hard to work with. I think it will be easier to build in functionality for specifics, one by one, so the scope is clear. 

As pymagicc is now tightly coupled to the development of magicc via the tests, eventually it will need to have the ability to modify every single one of magicc's input files. Hence this issue isn't really one of if/it would be great to have, rather when.

**Comment by rgieseke** [comment]
>So do you foresee a "custom" magicc7 distribution to be bundled in pymagicc as well? Custom in the sense that the bundled config/tunings are stripped down to the essentials and made to work out of the box with pymagicc. MAGICC7 install externally to pymagicc would still require manual setup as the USER namelist doesn't integrate with pymagicc.

I hope that this will be the case, rather sooner than later, otherwise we wouldn't have to worry so much about getting interfaces right :-) (An internal tool can probably change and break faster ...)

**Comment by rgieseke** [comment]
> I think it will be easier to build in functionality for specifics, one by one, so the scope is clear.

Agreed, let's keep this open as a meta issue and open specific PRs for inputs that are actually needed.

As a user I'd like to be able to see the actual (historical) inputs used with MAGICC, e.g. something like

```python
magicc = MAGICC()
magicc.histrcp_co2b_emis
```
which would give me a nice DataFrame from the respective file.
Ideally (some of) the metadata info would be stored in the DataFrame as well, maybe in _metadata or as a separate field 
```python
magicc.histrcp_co2b_emis_info
```

**Comment by znicholls** [comment]
Let's do this together today if you have time,, I'll be in an hour

**Comment by rgieseke** [comment]
More detailed discussion continues in #41

**Comment by znicholls** [comment]
Decided against this comment @rgieseke ? 

'Agreed, let's keep this open as a meta issue and open specific PRs for inputs that are actually needed.'

Or have I ruined it by opening my own meta issue?

**Comment by rgieseke** [comment]
Haha,  just forgot I put this here :-) The new issue seems much more purposeful!
