### ISSUE TITLE
Config writing

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#39]
The config file writing currently done in `pymagicc.run` should become part of the API

**Comment by lewisjared** [comment]
I propose adding:
* `MAGICC.write_config(filename='MAGTUNE_SIMPLE.CFG', top_level_key='nml_allcfgs', **kwargs)`
Which writes all additional arguments under the 'top_level_key' to a fortran namelist specified by the filename parameter.
e.g. `magicc.write_config(file_emisscen='RCP85.SCEN')` would write out a MAGTUNE_SIMPLE.CFG which contains the equiv of {'NML_ALLCFGS': {FILE_EMISSCEN: 'RCP85.SCEN'}}.

And a helper to create the NMLYEARS file
* `MAGICC.write_years(start_year=1765, end_year=2100, **kwargs)`

It would great to add calls for both of these functions to `MAGICC.create_copy` so a sane MAGCFG_NMLYEARS.CFG and MAGTUNE_SIMPLE.CFG is created. It would be nice if MAGICC ran out of the box with:
```
with MAGICC() as magicc:
     magicc.run()
```

**Comment by rgieseke** [comment]
That looks nice! Maybe `set_config` and `set_years`, anticipating a future MAGICC version with direct API access?
