### ISSUE TITLE
Improve API docs

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#57]
- review doc strings
- check config module
- maybe split in separate files and link to them from Readme

**Comment by znicholls** [comment]
@rgieseke can this be closed?

**Comment by rgieseke** [comment]
Can we close this or can I do this? ;-)

**Comment by znicholls** [comment]
Ok we leave it open then

**Comment by rgieseke** [comment]
We might consider switching to Sphinx (as used for Pyhector or OpenSCM, @swillner working on it) - it can use Markdown, see e.g. `black`'s docs: https://github.com/ambv/black/tree/master/docs

**Comment by znicholls** [comment]
sorry I commented in #134 but probably belongs here...

**Comment by znicholls** [comment]
Closing in favour of #134
