### ISSUE TITLE
Assigning different MAGICC versions

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#60]
In the docs we have, 

### Using a different MAGICC version

*Robert and Jared I'm pretty sure this isn't true anymore?*

The `_magiccpath` and `_magiccbinary` can be changed to point to different MAGICC
development versions.

Is this still true?

**Comment by lewisjared** [comment]
The variables are still in there, but changing them won't change the MAGICC package used

**Comment by lewisjared** [comment]
They are currently used to load the RCP SCEN files. These files should be lazy-loaded once the Input class can handle SCEN and SCEN7 files, removing the need for these variables.

**Comment by znicholls** [comment]
Reactivate once #49 is complete

**Comment by rgieseke** [comment]
I think we fixed this by removing the `_magiccbinary` var, feel free to reopen if necessary.
