### ISSUE TITLE
MAGICC_EXECUTABLE environment variable

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#61]
Is it `MAGICC_EXECUTABLE` or `MAGICC_EXECUTABLE_7`

**Comment by lewisjared** [comment]
MAGICC_EXECUTABLE_7 for MAGICC7
MAGICC_EXECUTABLE for MAGICC6

MAGICC_EXECUTABLE_6 would make more sense

**Comment by rgieseke** [comment]
Do we actually need a MAGICC_EXECUTABLE_6? Nobody is likely to develop on this anymore, right? Maybe we can just have "7" for people testing different versions of the current development branch?

**Comment by znicholls** [comment]
I would like to keep it in case people have different magicc6 executables
which we want to compare (seems possible). I'd prefer to drop
MAGICC_EXECUTABLE as I don't know what that is..
