### ISSUE TITLE
Plot in README.md

### ISSUE THREAD

**Issue by lewisjared** [openclimatedata/pymagicc#63]
The current image in README.md shows the old scenario names:
![image](https://github.com/openclimatedata/pymagicc/blob/master/scripts/example-plot.png?raw=true)

When running the code mentioned to create this plot, I get the following:
![image](https://user-images.githubusercontent.com/1332673/42005804-d344dcc4-7ab9-11e8-9b44-fe4e407f98c0.png)

Obviously there is some style differences. Perhaps @rgieseke can regenerate the plot with the correct size and style.

**Comment by rgieseke** [comment]
Good catch! The script is in `scripts` and I've also added a task to the Makefile.
It's using `plt.style.use("ggplot")`.

I'll need to automate even more of the release process ...
