### ISSUE TITLE
Python 3.7 testing

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#64]
We should add testing with Python 3.7 and consider dropping 3.5 from the CI. Is anyone still stuck on 3.5? @lewisjared @znicholls

**Comment by znicholls** [comment]
I have no idea what I'm using but can easily change with venv etc (I don't
use pymagicc for any analysis yet...)

**Comment by rgieseke** [comment]
With `brew` it's usually up-to-date -- what is Gitlab CI's default Linux runner using? If it's an older stable release, it might be good to ensure no problems with 3.5, otherwise I'd be happy to speed up checks.

**Comment by lewisjared** [comment]
3.5 is the default python3 version on ubuntu 16.04. Personally, I use
anaconda so that doesn't affect me.

Gitlab uses docker containers for environments. The magicc CI pipeline uses
the `python:3.6` image

Saving a few cycles isn't a good reason to drop support in my opinion.

**Comment by rgieseke** [comment]
Alright ... let's keep 3.5 then, at least for a while!

**Comment by znicholls** [comment]
I'm with Jared, why is dropping version support useful?
