### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#65]
The release process needs to be written down and, ideally, automated more:

- check notebooks
- check plot
- cut release for Zenodo tagging

**Comment by znicholls** [comment]
@rgieseke i can't see an easy way to automate the zenodo release process, do you have any ideas? Also what doesn't 'cut the release' mean?

**Comment by rgieseke** [comment]
I don't know if it's possible to automate (probably good to not do automatically, as the archived version with doi will stay up).

It means clicking on "Do relase" on GitHub. Once it's a "release" - not just a tag it will get picked up from Zenodo.

**Comment by znicholls** [comment]
closed by #167
