### ISSUE TITLE
Region names

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#69]
At the moment MAGICC input files use a mix of region names. In the API I figure we may as well make them all come out the same for the regions which are equivalent. Hence how do we feel about always using:

'GLOBAL' rather than 'WORLD'
'RASIA', 'RREF' etc. rather than 'R5ASIA', 'R6ASIA', 'R5REF', 'R6REF' (or should we actually keep these separate because their definitions are, in a very minor way, different and instead just allow people to access both 'R5ASIA' and 'R6ASIA' with 'RASIA' depending on what is in the dataframe)

**Comment by rgieseke** [comment]
Not sure I understand the question ... is this more of a MAGICC problem, and we're talking about how to wrap/simplify this in Pymagicc?

**Comment by znicholls** [comment]
> Not sure I understand the question ... is this more of a MAGICC problem, and we're talking about how to wrap/simplify this in Pymagicc?

exactly. MAGICC is currently awkward and will be super hard to fix so I figure that we can just abstract away the issues (for now)

**Comment by rgieseke** [comment]
Alright, if you have good ideas, go for it! But it would be good to keep in mind that potential users might be used to/rely on the old names, e.g. IAM users maybe?. Does "pyam" do something in this regard?

In any case we should provide a mapping dict to let people quickly move between the systems.

Maybe @AnnisG or @mljeffery have ideas?

**Comment by AnnisG** [comment]
I would not change the region names, I think they are defined in the IPCC reports and thus sort of a standard. Atleast the RC5 regions are, not sure if the R5 and R6 regions are define din the IPCC reports, too.

**Comment by znicholls** [comment]
`pyam` down- and up-scales all the native model regions to a common set of regions so they only have one definition to deal with.

At the moment we have two definitions, `R5` and `R6`. @AnnisG as far as I can tell `R6` is identical to PRIMAP's `R5.2` (I'm not sure why we used `R6`). Admittedly they aren't actually the same thing, but for most purposes they are so similar that having to make different calls is annoying. So it seems like a sensible path forward is (?):

- don't change region names
- provide a simple mapping dict so users can make calls like `magicc_df.plot('ASIA')` and it will just plot the most sensible region (i.e. either `R5ASIA` or `R6ASIA` depending on what is available)

**Comment by AnnisG** [comment]
That sounds good to me.

**Comment by mljeffery** [comment]
sounds good to me too. Best to keep it clear if someone wants to be sure what they're using, but the convenience option sounds great for every day use.

**Comment by znicholls** [comment]
Should be solved by moving to using the `openscm` API

**Comment by znicholls** [comment]
Closed by #154 and #170 which now allow users to do e.g. `filter(region="*ASIA*")`
