### ISSUE TITLE
Accessing MAGICC input data

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#74]
**Is your feature request related to a problem? Please describe.**

At the moment I don't know what a sensible way to provide access to dataframe data is. Using a multi-indexed frame can make things pretty nasty.

**Describe the solution you'd like**

It'd be good to have some sort of wrapper included in #49 which makes it easy for users to access data through our api. I'm not sure what the best way for that to look is. It seems like now is a good time to define how we want it to look/behave, given it's not built yet.

I'm guessing we probably want to be able to do things like:

```
minput.df.loc['ASIA', 'CO2_CONCS']
```

and have sensible values returned (in this case a dataframe, the values of which could then be extracted with `.values`). At the moment you have to specify every 'dimension' (e.g. `minput.df.loc['ASIA', 'CO2_CONCS', 'SET', 'ppm', slice(2015,2100)]` to get data and I don't think that should be the case).

**Describe alternatives you've considered**

We could just force all users to learn how to use multi-indexed dataframes but that seems contrary to the spirit of the project.

**Comment by znicholls** [comment]
@rgieseke your comments would be especially appreciated as you've thought about this a lot more than me

**Comment by rgieseke** [comment]
Hmm, if you have a clear hierarchy of data you could build something with [dataclasses](https://realpython.com/python-data-classes/) maybe? (There is a backport to 3.6)

What is the problem you are trying to solve? Do you need to say

`CO2_CONCS.ASIA` and `CO2_CONCS.EUROPE` _and_ `ASIA.CO2_EMISSIONS` and `ASIA.CO2_CONCS`?

**Comment by znicholls** [comment]
I'm trying to work out how we should give access to our data without making our users know that e.g. CO2_CONCS are in ppm whilst making sure that our dataframes include the units.

So, for example, currently things are set up such that if you want to get a single value you need to access, `minput.df.loc['ASIA', 'CO2_CONCS', 'SET', 'ppm', slice(2015,2100)]`. This seems stupid to me and I would rather have it such that `minput.df.loc['ASIA', 'CO2_CONCS', slice(2015,2100)]` returned a single value. However I'm not sure if that's what we want so have opened this issue.

**Comment by znicholls** [comment]
should be solved in #102
