### ISSUE TITLE
Standardising variable names

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/pymagicc#75]
**Is your feature request related to a problem? Please describe.**

At the moment the native variable names are all over the place and not always that descriptive e.g. `CO2B_EMIS` doesn't really tell you anything.

**Describe the solution you'd like**

Defining a set of mapping dictionaries to change MAGICC's raw output to nicer names. I'm not sure how exactly this would look. I don't know if it's better to have trees so you access things with e.g. `output['emissions']['co2']['AFOLULUC']` or delimited variable names e.g. `output['emissions-co2-AFOLULUC']`. In both cases having standardisation across variables should make life easier.

**Describe alternatives you've considered**

Sticking with the native variable names. I don't like this because they're not that descriptive.

**Comment by rgieseke** [comment]
In principle, I completely agree, but I'm not sure if Pymagicc should be mostly *just* MAGICC but with Python -- I think a first step could be to build a nice API in a separate repo with the main relevant inputs and outputs mapped ...

**Comment by znicholls** [comment]
Sounds sensible. Would make more sense for the wrapper too!

**Comment by znicholls** [comment]
#102 makes some steps towards this with its `convert_MAGICC6_to_MAGICC7_variables` function...

**Comment by znicholls** [comment]
Should be solved by moving to using the `openscm` API

**Comment by rgieseke** [comment]
So, let's close this for now?
