### ISSUE TITLE
Missing Output files

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/pymagicc#86]
Like `CARBONCYCLE.OUT` output discussed in #84, #85 there are a few other outputs not named `DATSOMETHING.OUT` -- should we read them all or add them as we go when someone actually needs them?

Thought @znicholls @NortonAlex ?

**Comment by znicholls** [comment]
Probably requires a sprint on #49 

Once that's in, we can just add classes to `pymagicc/input.py` for every new file we need and things will be much simpler (he says hopefully)

**Comment by safiume** [comment]
I was able to get the all the other files named *.OUT by swapping out the filename replace with a regular expression to update the variable name only. Advantages are it also doesn't change the filesytem with a file rename and it only strips off the name that will be accessed by pandas. It does work for strip off DAT, DAT_ and captures everything up to the .OUT. It may need a conditional test to catch if there aren't any .OUT files.

`+            name = re.search(r'(?:DAT[_]?)?(.*).OUT', filename)[1]
`

**Comment by rgieseke** [comment]
@safiume That looks like a very good approach! Do you want to submit a PR?

**Comment by safiume** [comment]
Patch? Or pull request?
It works for getting the data into a dataframe, but heading lines don't match up and confuse pandas. I haven't had luck at resetting the indexes to get at the data. Do you still want this change as a single commit or wait till the header is readable to allow trival access to the dataframe?

**Comment by rgieseke** [comment]
If it's not working fully yet, probably better to wait, as @znicholls suggested.

**Comment by rgieseke** [comment]
@znichols Can this be closed?

**Comment by znicholls** [comment]
Yes #107 is the right issue now
