### ISSUE TITLE
no run_tests.py available as indicated in Readme.

### ISSUE THREAD

**Issue by matthiasmengel** [openclimatedata/pymagicc#91]
I tried to "use a different MAGICC version" following

"""
#!/bin/bash
export MAGICC_EXECUTABLE_7=tmp/magicc/run/magicc.exe
python run_tests.py
python generate_plots.py
"""
from Readme.md

However, a `run_tests.py` file does not exist, nor does a `generate_plots.py`.

Could you update this section?

**Comment by rgieseke** [comment]
Good point. These examples assume that you have a `run_tests.py` script ...

Not sure what the best example is.
We could just use

`make test`

Would that work?

```
#!/bin/bash
export MAGICC_EXECUTABLE_7=tmp/magicc/run/magicc.exe
make test
```

**Comment by matthiasmengel** [comment]
This works. The virtual environment is successfully built. I then arrive at #92. 
`make test` is kind of big and probably intimidating for some. How did the `run_tests.py` look like?
There are people who know python, but not make.

**Comment by rgieseke** [comment]
Yes, we should find a workable example for the Readme, maybe the `generate_plots.py` which should run. Just to ensure that it works in principle. Or even better, a simple script which just prints the MAGICC `version`.

**Comment by znicholls** [comment]
isn't this what the notebooks are for?

**Comment by rgieseke** [comment]
Could just be a simple script that enables you to check (or debug someone else's setup) whether the environment var works.

**Comment by znicholls** [comment]
> Could just be a simple script that enables you to check (or debug someone else's setup) whether the environment var works.

Alright. I don't like the duplication but I can see why it's worth it.
